"""Generated page docs/appendix/openhab-comparison.md: the openHAB binding's robot enumerations compared by script with the bundle tables.
Sources: data/openhab_robot_enums.json (commit recorded in the file), data/enums.json, data/consumables.json, data/models.json.
Verdict column: `agree` = the openHAB label shares a word with the app's name/title/detail of the code; `differs` = no common word (read both);
`openHAB only` / `bundles only` = the code exists on one side only."""
import json
import re


def toks(s):
    return {w for w in re.findall(r'[a-z]{4,}', (s or '').lower())}


def latest(ctx, groups):
    best = max(groups, key=lambda g: max((ctx.best[b]['sdk_api_level'] or 0, ctx.best[b]['build_date_utc'] or '') for b in g[1]))
    return best[0]


def run(ctx, G):
    oh = G.load_json('openhab_robot_enums.json')
    meta = oh['openhab']
    en = G.load_json('enums.json')
    ref = 'compared with the openHAB miio binding at `%s` (ref `%s`, %s)' % ((meta['commit'] or '?')[:10], meta['ref'], meta['commit_date'] or 'date unknown')
    L = ['# openHAB binding comparison', '', '[Home](../../README.md) / [Appendix](index.md) / openHAB comparison', '',
         'Generated by script: ' + ref + '. The binding is a cross-check source only (🔶 openHAB); where it disagrees with the bundles the bundles win ([corrections](corrections.md#bundle-vs-openhab-conflicts)). '
         'Verdict: `shared wording` = the openHAB label shares a word with the app wording for the code, `wording differs` = no common word (usually only another wording; read both), `openHAB only` / `bundles only` = the code exists on one side only. Real disagreements are collected in the [corrections](corrections.md#bundle-vs-openhab-conflicts).', '']
    # ---- states
    st = {s['code']: s for s in en['states']}
    L += ['## States (`StatusType`)', '', '| Code | openHAB | Bundles (constant: newest wording) | Verdict |', '|---:|---|---|---|']
    ohs = {int(k): v for k, v in oh['enums']['StatusType'].items()}
    for c in sorted(set(ohs) | set(st)):
        s = st.get(c)
        txt = ''
        if s:
            txt = '`%s`: %s' % (s['constant'], latest(ctx, [(n['text'], n['bundles']) for n in s['names']]) or '—')
        if c in ohs and s:
            v = 'shared wording' if toks(ohs[c]) & toks(txt) or ohs[c].lower() in txt.lower() else 'wording differs'
        else:
            v = 'openHAB only' if c in ohs else 'bundles only'
        L.append('| %d | %s | %s | %s |' % (c, ohs.get(c, ''), txt, v))
    # ---- errors
    er = {e['code']: e for e in en['errors']}
    L += ['', '## Errors (`VacuumErrorType`)', '', '| Code | openHAB | Bundles (internal name: title) | Verdict |', '|---:|---|---|---|']
    ohe = {int(k): v for k, v in oh['enums']['VacuumErrorType'].items() if int(k) >= 0}
    only_b = []
    for c in sorted(set(ohe) | set(er)):
        e = er.get(c)
        txt = ''
        if e:
            groups = [(json.dumps(x['entry'], sort_keys=True), x['bundles']) for x in e['entries']]
            ent = json.loads(latest(ctx, groups))
            title = ent.get('title')
            if isinstance(title, dict):
                title = '(depends on the product)'
            title = re.sub(r'\{[A-Za-z0-9_]+\}', '(no English string)', title or '')
            txt = '`%s`: %s' % (ent['name'], title)
            full = ' '.join(str(ent.get(k) or '') for k in ('name', 'title', 'subtitle', 'detail'))
        if c in ohe and e:
            v = 'shared wording' if toks(ohe[c]) & toks(full) else 'wording differs'
        else:
            v = 'openHAB only' if c in ohe else 'bundles only'
        if v == 'bundles only':
            only_b.append(c)
            continue
        L.append('| %d | %s | %s | %s |' % (c, ohe.get(c, ''), txt, v))
    L += ['', 'Codes that only the bundles know (%d): %s.' % (len(only_b), ', '.join(str(c) for c in only_b)), '']
    # ---- fan
    ohf = {int(k): v for k, v in oh['enums']['FanModeType'].items() if int(k) >= 0}
    seen = {}
    for name in ('CleanModeMap', 'CleanModeMapOld'):
        for row in en['fan_tables'].get(name, []):
            for k, v in row['table'].items():
                if v and k.isdigit():
                    seen.setdefault(int(k), set()).add(str(v))
    L += ['## Fan modes (`FanModeType`)', '', '| Code | openHAB | Bundles (labels seen) | Verdict |', '|---:|---|---|---|']
    for c in sorted(ohf):
        b = sorted(seen.get(c, []))
        v = ('shared wording' if toks(ohf[c]) & toks(' '.join(b)) or ohf[c].lower() in ' '.join(b).lower() else 'wording differs') if b else 'openHAB only'
        L.append('| %d | %s | %s | %s |' % (c, ohf[c], ', '.join(b), v))
    # ---- consumables
    cons = {c['key']: c for c in G.load_json('consumables.json')['consumables']}
    life = {k: max((v['total'] or 0) for v in c['variants']) for k, c in cons.items()}
    ohc = oh['enums']['ConsumablesType']
    L += ['', '## Consumable lives (`ConsumablesType`)', '', '| Hours (openHAB) | openHAB name | Bundles: key with that nominal life | Verdict |', '|---:|---|---|---|']
    for c, n in sorted(ohc.items(), key=lambda kv: -int(kv[0])):
        if int(c) == 0:
            continue
        keys = [k for k, t in life.items() if t == int(c) and cons[k]['variants'][0]['units_time']]
        L.append('| %s | %s | %s | %s |' % (c, n, ', '.join('`%s`' % k for k in keys), 'shared wording' if keys else 'wording differs'))
    # ---- dock
    ohd = {int(k): v for k, v in oh['enums']['DockStatusType'].items() if int(k) >= 0}
    L += ['', '## Dock status (`DockStatusType`) against the dock error codes', '', '| Code | openHAB | Bundles (internal name: title) | Verdict |', '|---:|---|---|---|']
    for c in sorted(ohd):
        e = er.get(c)
        if e:
            ent = json.loads(latest(ctx, [(json.dumps(x['entry'], sort_keys=True), x['bundles']) for x in e['entries']]))
            t = ent.get('title') if not isinstance(ent.get('title'), dict) else ''
            full = ' '.join(str(ent.get(k) or '') for k in ('name', 'title', 'subtitle', 'detail'))
            L.append('| %d | %s | `%s`: %s | %s |' % (c, ohd[c], ent['name'], re.sub(r'\{[A-Za-z0-9_]+\}', '(no English string)', t or ''), 'shared wording' if toks(ohd[c]) & toks(full) else 'wording differs'))
        else:
            L.append('| %d | %s | — | openHAB only |' % (c, ohd[c]))
    # ---- names
    mods = G.load_json('models.json')['bundled']
    mods = mods if isinstance(mods, list) else list(mods.values())
    L += ['', '## Model names', '', 'Models of the bundled set whose openHAB name differs from the Mi Home cloud device catalog name, or that the binding does not list:', '',
          '| Model | openHAB | Catalog | Legacy text |', '|---|---|---|---|']
    for m in sorted(mods, key=lambda x: G.natkey(x['id'])):
        cat = sorted({c['name'] for c in m['names'].get('catalog', [])})
        o = m['names'].get('openhab')
        if (o and cat and o not in cat) or not o:
            L.append('| `%s` | %s | %s | %s |' % (G.short(m['id']), o or '(not listed)', ' / '.join(cat), m['names'].get('legacy') or ''))
    L += ['', '## See also', '', '- [Corrections](corrections.md#bundle-vs-openhab-conflicts)', '- [Unverified models](unverified-models.md)', '']
    G.OUT['docs/appendix/openhab-comparison.md'] = '\n'.join(L)
